### ISSUE TITLE
Kick false player

### ISSUE THREAD

**Issue by Bara** [neatek/GameVoting#11]
https://github.com/neatek/GameVoting/blob/b9317089b9ad1347a26c745c742a28f0c690f13c/addons/sourcemod/scripting/GameVoting/GameVoting.sp#L380
and
https://github.com/neatek/GameVoting/blob/b9317089b9ad1347a26c745c742a28f0c690f13c/addons/sourcemod/scripting/GameVoting/GameVoting.sp#L399

victim instead of client?

**Comment by neatek** [comment]
Fixed.
