### ISSUE TITLE
Error in translation

### ISSUE THREAD

**Issue by pro100it** [neatek/GameVoting#15]
GameVoting/addons/sourcemod/translations/ru/phrases.GameVoting.txt

> "GameVoting_antiflood"
> 	{
> 		"#format" "{1:s},{2:d}"
> 		"en" "{1} Пожалуйста не флуди, подожди {2} сек."
> 	}

**"GameVoting_antiflood"
	{
		"#format" "{1:s},{2:d}"
		"ru" "{1} Пожалуйста не флуди, подожди {2} сек."
	}**

**Comment by neatek** [comment]
Oh, yeah - error, but not critical)

**Comment by pro100it** [comment]
Yep! not critical )

**Comment by neatek** [comment]
gv1.8 doesnt have translations.
will be soon.
