### ISSUE TITLE
GOTV

### ISSUE THREAD

**Issue by TR1D** [neatek/GameVoting#16]
GameVoting (1.8.2dev)
Неплохо бы убрать GOTV из списка игроков.
![20170505011503_1](https://cloud.githubusercontent.com/assets/16725731/25727264/fad6566a-3130-11e7-8a7d-fe3ad42e09af.jpg)

**Comment by neatek** [comment]
Уберём

**Comment by neatek** [comment]
Поправлено в gv1.8
