### ISSUE TITLE
Restrict starting a vote to flag

### ISSUE THREAD

**Issue by PetriVukan** [neatek/GameVoting#18]
Hi,

It would be cool to have a feature where only certain players, with flag "r" for example, are allowed to start a vote. But everyone else can vote yes or no, even if they do not have the flag "r".

So for example: a VIP with the flag "r" types !votemute and selects a player. Players are then prompted with a window:

_Do you want to mute "example"?

1. Yes
2. No_

They can press 1 or 2 inorder to vote.

**Comment by neatek** [comment]
It's a good idea. Thank you!

**Comment by PetriVukan** [comment]
Thank you for taking your time to code this great plugin!

**Comment by neatek** [comment]
Yep, 1.8.3 is now here!
but this feature will be soon.

**Comment by neatek** [comment]
Added in current version.
check it!

gamevoting_startvote_flag",	"" //	"Who can start voting for ban or something, set empty for all players (def:a)
gamevoting_startvote_delay", "20" // Delay between public votes in seconds (def:20)
