### ISSUE TITLE
gamevoting_players 2. не удается запустить голосование при 4х игроках

### ISSUE THREAD

**Issue by usershtopor** [neatek/GameVoting#21]
версия плагина 1.8.4 dev от 4 августа
sm 1.8.0.6015

онлайн на сервере 4 человека. все реальные люди
gamevoting_players "2", но при этом голосование voteban, votekick и votemute не работают
в чате пишет, что будет доступно при 2х игроках

**Comment by neatek** [comment]
Скорей всего у них просто иммунитеты, и игроков не хватает для открытия меню.
Игроки с иммунитетом не учитываются.

**Comment by usershtopor** [comment]
CONVAR_VERSION = CreateConVar("sm_gamevoting_version", 					VERSION, 	"Version of gamevoting plugin. DISCORD - https://discord.gg/J7eSXuU , Author: Neatek, www.neatek.ru", FCVAR_SPONLY|FCVAR_REPLICATED|FCVAR_NOTIFY);
	CONVAR_ENABLED = CreateConVar("gamevoting_enable",							"1", 	"Enable or disable plugin (def:1)", _, true, 0.0, true, 1.0);	

	// min players
	CONVAR_MIN_PLAYERS = CreateConVar("gamevoting_players",						"2",	"Minimum players need to enable votes (def:8)", _, true, 0.0, true, 20.0);
	CONVAR_AUTODISABLE = CreateConVar("gamevoting_autodisable",					"0",	"Disable plugin when admins on server? (def:0)", _, true, 0.0, true, 1.0);

	// disables
	CONVAR_BAN_ENABLE = CreateConVar("gamevoting_voteban",						"1",	"Enable or disable voteban functional (def:1)", _, true, 0.0, true, 1.0);
	CONVAR_KICK_ENABLE = CreateConVar("gamevoting_votekick",					"1",	"Enable or disable votekick (def:1)", _, true, 0.0, true, 1.0);
	CONVAR_MUTE_ENABLE = CreateConVar("gamevoting_votemute",					"1",	"Enable or disable votemute (def:1)", _, true, 0.0, true, 1.0);
	//CONVAR_SILENCE_ENABLE = CreateConVar("gamevoting_votesilence",			"1",	"Enable or disable silence (def:1)", _, true, 0.0, true, 1.0);

	// durations
	CONVAR_BAN_DURATION = CreateConVar("gamevoting_voteban_delay", 				"10", 	"Ban duration in minutes (def:120)", _, true, 0.0, false);
	CONVAR_KICK_DURATION = CreateConVar("gamevoting_votekick_delay", 			"20", 	"Kick duration in seconds (def:20)", _, true, 0.0, false);
	CONVAR_MUTE_DURATION = CreateConVar("gamevoting_votemute_delay", 			"10", 	"Mute duration in minutes (def:120)", _, true, 0.0, false);
	//CONVAR_SILENCE_DURATION = CreateConVar("gamevoting_votesilence_delay", 	"1", 	"Mute duration in minutes (def:120)", _, true, 0.0, false);

	// percent
	CONVAR_BAN_PERCENT = CreateConVar("gamevoting_voteban_percent",				"50",	"Needed percent of players for ban someone (def:80)", _, true, 0.0, true, 100.0);
	CONVAR_KICK_PERCENT = CreateConVar("gamevoting_votekick_percent", 			"50",	"Needed percent of players for kick someone (def:80)", _, true, 0.0, true, 100.0);
	CONVAR_MUTE_PERCENT = CreateConVar("gamevoting_votemute_percent", 			"50",	"Needed percent of players for mute someone (def:75)", _, true, 0.0, true, 100.0);
	//CONVAR_SILENCE_PERCENT = CreateConVar("gamevoting_votesilence_percent",	"75",	"Needed percent of players for silence someone (def:75)", _, true, 0.0, true, 100.0);
	
	// Immunity flags
	CONVAR_IMMUNITY_FLAG = CreateConVar("gamevoting_immunity_flag",				"",		"Immunity flag from all votes (def:a)");
	CONVAR_IMMUNITY_zFLAG = CreateConVar("gamevoting_immunity_zflag",			"0",	"Immunity for admin flag \"z\"");

	CONVAR_START_VOTE_ENABLE = CreateConVar("gamevoting_startvote_enable", 		"1", 	"Disable of enable public votes (def:1)", _, true, 0.0, true, 1.0);
	CONVAR_FLAG_START_VOTE = CreateConVar("gamevoting_startvote_flag",			"",		"Who can start voting for ban or something, set empty for all players (def:a)");
	CONVAR_START_VOTE_DELAY = CreateConVar("gamevoting_startvote_delay", 		"20", 	"Delay between public votes in seconds (def:20)", _, true, 0.0, false);

**Comment by neatek** [comment]
gamevoting_immunity_flag "" не работает с пустым.
