### ISSUE TITLE
Меню с вариантами ответа

### ISSUE THREAD

**Issue by TR1D** [neatek/GameVoting#22]
Смотрю в новой версии, после первого проголосовавшего, появляется меню с вариантами да-нет.
Это конечно удобно, но чаще всего приводит к баловству и ложным наказаниям.
В предыдущих версиях для удачного наказания необходим голос каждого, с вводом команды в чате.
Именно не столь быстрый процесс, с обязательный вводом команды каждым игроком, помогал от поспешных решений игроков.
Цифры (1-2) используются для переключения оружия, как следствие ложные нажатия.

**Comment by TR1D** [comment]
Не будет верным убрать меню для быстрого опроса каждого, но неплохо бы получить квар с отключением "соц опроса на линчевание".

**Comment by neatek** [comment]
В сегодняшней версии цифры 1 2 заменены. 
Также можно отключить startvote. (уже с версии 1.8.4 вроде)

**Comment by neatek** [comment]
gamevoting_startvote_enable 0

**Comment by TR1D** [comment]
Спасибо, то что нужно.
