### ISSUE TITLE
/ перед командой

### ISSUE THREAD

**Issue by TR1D** [neatek/GameVoting#23]
Все еще имеется проблема с символом "/".
На сколько я понимаю введенная таким образом команда конфликтует с basevotes.smx
```
	RegAdminCmd("sm_votemap", Command_Votemap, ADMFLAG_VOTE|ADMFLAG_CHANGEMAP, "sm_votemap <mapname> [mapname2] ... [mapname5] ");
	RegAdminCmd("sm_votekick", Command_Votekick, ADMFLAG_VOTE|ADMFLAG_KICK, "sm_votekick <player> [reason]");
	RegAdminCmd("sm_voteban", Command_Voteban, ADMFLAG_VOTE|ADMFLAG_BAN, "sm_voteban <player> [reason]");
	RegAdminCmd("sm_vote", Command_Vote, ADMFLAG_VOTE, "sm_vote <question> [Answer1] [Answer2] ... [Answer5]");
```

**Comment by neatek** [comment]
Да, есть такое. Но sourcebans отключается basevotes

**Comment by TR1D** [comment]
C sourcebans отключается basebans.smx

**Comment by TR1D** [comment]
PS. Как с изменением префикса сообщений ?

**Comment by neatek** [comment]
Префикс не меняется все работает и с / и с ! И без этого. И basevotes ругается но GameVoting все равно на эти ругательства. Так что это все работоспособно.

**Comment by TR1D** [comment]
В том то и дело, что при "/", меню с игроками нет.

**Comment by neatek** [comment]
Такого быть не может. Кинь адрес в дискорд.

**Comment by neatek** [comment]
Решено.
