### ISSUE TITLE
Start Vote

### ISSUE THREAD

**Issue by wasyady** [neatek/GameVoting#26]
I think gamevoting_startvote_enable 1, dosn't working.

Error log:

> L 08/12/2017 - 15:58:51: Info (map "de_inferno") (file "errors_20170812.log")
> L 08/12/2017 - 15:58:51: [gv18.smx] Error! Folder /logs/gamevoting/ doesnt exists! Please, create it to enable logs.
> L 08/12/2017 - 16:19:58: Error log file session closed.

The folder exists!

Win2008R2, SRCDS running with administrator permission.

**Comment by neatek** [comment]
Yeah. I know about this issue. It's only on Windows... I'll check it

**Comment by neatek** [comment]
Can you test latest Commit? 
Repository was updated.

**Comment by wasyady** [comment]
Log problem resolved!

**Comment by wasyady** [comment]
Vip's vote start dosn't working! :(

**Comment by neatek** [comment]
vip vote? wtf.
give some more info

**Comment by wasyady** [comment]
I misunderstand the vote initiative.
I thought ,It would start a vote like the admins.
Is this possible ?

**Comment by neatek** [comment]
try

```
gamevoting_startvote_flag "a"
gamevoting_startvote_delay "10"
gamevoting_startvote_min "0"
```

it will be always `voteban` for generic admins (a flag) with `StartVote`, without any restrictions.
suggest it will be works. i dont know)
just try it, and let me know.

* `StartVote` - it is a name of feature, use it.

**Comment by neatek** [comment]
alo?
