### ISSUE TITLE
voteban

### ISSUE THREAD

**Issue by lucky84** [neatek/GameVoting#3]
you can add, voteban reasons?

Optionally make players specify a reason for votebanning someone. The most-selected reason is then logged when the ban takes effect.

**Comment by neatek** [comment]
okay, i need more features for release.
btw, i want to know about all issues in current release 1.7.4hf-dev.
please hardtest it, and give me feedback. thx.

**Comment by lucky84** [comment]
Ok, Thx :)

**Comment by neatek** [comment]
# GameVoting 1.7.5 feature №1

Voteban reasons:
https://forums.alliedmods.net/showpost.php?p=2269746&postcount=152

![GameVoting Reason](https://leto14h.storage.yandex.net/rdisk/49f6fcbff76ebec83117c1ce31d802b303c6db7926b328b79fbdf83b3bbe4972/inf/5ouh6HU04TjhZVotf8g0ZEPv_bzzivbwrQeuQ7neCrSs3P3vNE8vnNj8iOA8SWFXRP6zcrE52__YhqdCn_-BUg==?uid=0&filename=gv.jpg&disposition=inline&hash=&limit=0&content_type=image%2Fjpeg&tknv=v2&rtoken=63a17988383704fdc676ec6364469d16&force_default=no)

**Comment by neatek** [comment]
## GameVoting 1.7.5-dev Pre-release

**Released**: https://forums.alliedmods.net/attachment.php?attachmentid=143002&d=1425809659
- Voteban reasons.
- Private flag.
