### ISSUE TITLE
Reason

### ISSUE THREAD

**Issue by lucky84** [neatek/GameVoting#30]
I have last GameVoting 1.8.8, when players make voting there's no reason and in sourcebans it looks like this

Gamevoting (Kronos)(Empty reason)

Public voting is OFF and game is CS:S

**Comment by usershtopor** [comment]
Hi,
I confirm this bug

check banlist
http://sourceclub.ru/bans/index.php?p=banlist

there are no errors in the error logs

CSGO
Sourcemod 1.9.0 6241
Sourcebans++ 1.6.3
GameVoting 1.8.8

My config:
gamevoting_authid "1"
gamevoting_autodisable "0"
gamevoting_enable "1"
gamevoting_immunity_flag "d"
gamevoting_immunity_zflag "1"
gamevoting_logs "1"
gamevoting_players "4"
gamevoting_startvote_delay "20"
gamevoting_startvote_enable "1"
gamevoting_startvote_flag ""
gamevoting_startvote_min "4"
gamevoting_voteban "1"
gamevoting_voteban_delay "120"
gamevoting_voteban_percent "70"
gamevoting_votekick "1"
gamevoting_votekick_delay "60"
gamevoting_votekick_percent "60"
gamevoting_votemute "1"
gamevoting_votemute_delay "120"
gamevoting_votemute_percent "60"
