### ISSUE TITLE
Reasons dont work

### ISSUE THREAD

**Issue by trollollol123** [neatek/GameVoting#31]
I dont get any options to give reasons when I start a vote.  No errors.

**reasonfile:**
Cheating Player
AFK Player
Toxic Player

**Comment by TandelK** [comment]
@BrutalCSEjziponken Are you having Admin rights on the server ? Because Admin has inbuilt vote functions of Kicking and Banning but that does not show any reasons. If people type !votekick <PlayerName> and depending on the ratio it will shows you the information.

**Comment by Allower** [comment]
The bug with reasons really have all who use latest version of GV.

On my server any player without or with rights who types voteban/kick/mute and sucessfully voted have no his reason on SourceBans

**Comment by neatek** [comment]
Yes, i know about that issue, but now i have no time to fix it. (also its not a critical bug)
I support this plugin only 1 time in year for free, for all.

if you want to improve speed of update you can make some donate:
https://www.paypal.me/neatek/5
https://qiwi.me/neatek
https://neatek.ru/gvsupport
https://pezy.ru/robokassa/?sum=500
