### ISSUE TITLE
Мут и Material Admin

### ISSUE THREAD

**Issue by kleuser75** [neatek/GameVoting#32]
Есть баг с совместимостью Material Admin.
Если человек был замучен админом, игроки могут написать на него votemute и мут сработает на нем, и по истечению votemut'a этот мут снимается. Можно ли как то оградить, или сделать проверку, если у человека есть мут, то votemute нельзя будет прописать ?

**Comment by neatek** [comment]
Индикация замьючен или нет через инклуд basevotes? Или у material admin свои инклуды в сорсниках?

**Comment by kleuser75** [comment]
эм, я без понятия, я даже не понял о чем ты )) я просто сообщил о проблеме

**Comment by kleuser75** [comment]
зачем закрыл, проблема то осталась.
можно хотя бы сделать проверку, если у человека есть уже мут, то на него нельзя было написать votemute

**Comment by neatek** [comment]
v1.9.2
- Supports MaterialAdmin
