### ISSUE TITLE
[Идея] Запуск голосования по набору n кол-ва голосов

### ISSUE THREAD

**Issue by kleuser75** [neatek/GameVoting#34]
Не знаю наверное уже нет смысла тут что-то писать, вроде поддержка остановилась, но всё же.
Было бы хорошо сделать запуск голосования, когда определенное кол-во голосов наберется
Например:
Люди пишут voteban, как наберется 50% к примеру, запускается голосование забанить или нет игрока.

**Comment by neatek** [comment]
Так вроде сейчас так и есть) там был какойто параметр в процентах, после числа определенного процента запускалось публичное голосование.

**Comment by kleuser75** [comment]
Ткни носом, что-то в упор не вижу. Вижу только минимальное кол-во игроков для запуска startvote, процентов не вижу

**Comment by neatek** [comment]
Ткнуть носом не могу, я делал это 2 года назад и уже вообще не помню что там есть, а чего нет) 😊 если бы конфиг был, я бы может быть и почитал что я там писал... но вроде как я делал такую штуку что если игроков больше 10 человек к примеру, и их них 80% набрало бан - то всем выводиться менюшка с баном игрока. Почитай конфиг внимательнее.

**Comment by kleuser75** [comment]
Там есть квар gamevoting_startvote_min это он ?
Просто описание в заблуждение вводит. 
> Minimum players for start \"startvote\" feature (def:4)

Складывается то, что нужно 4 человека для работы голосования, а не по набору 4 голосов что бы запустить это голосование. И почему конкретное кол-во, а не процент от голосующих.
