### ISSUE TITLE
[Feature Request] Add Vote Gag & Silence

### ISSUE THREAD

**Issue by crashzk** [neatek/GameVoting#36]
Currently he already has the Vote for Mute, it would be interesting to put the vote for Gag & Silence.

- Voting for Gag would be the Chat.
- Voting for Silence would be Voice & Chat.

Checking the plugin's source file, I saw that the Gag & Silence option has already been commented.

**Comment by neatek** [comment]
It was, but it added a misunderstanding, so it replaced by simple mute(gag+silence)
