### ISSUE TITLE
No Ban Entry

### ISSUE THREAD

**Issue by lucky84** [neatek/GameVoting#39]
Hi Neatek

Great Plugin but i have a problem. 1 player was Banned by voting, but gamevoting don't put it into sourcebans.

`L 02/12/2020 - 16:12:14: [gv.smx] Player BorisBorisovski([U:1:491853136]) voted for ban RONALDO([U:1:848312288]). (7/8)
L 02/12/2020 - 16:13:22: [gv.smx] Player madeinaustria([U:1:28577622]) voted for ban RONALDO([U:1:848312288]). (8/8)
L 02/12/2020 - 16:13:22: [gv.smx] Player RONALDO([U:1:848312288]) was banned by voting. (Last voted player: madeinaustria)
`

Game: CS:S
SourceMod Version: 1.10.0.6453 
Gamevoting Version: 1.9.0
Sourcebans Version: 1.4.11

![Anmerkung 2020-02-12 171309](https://user-images.githubusercontent.com/4884795/74354003-ffdab300-4dba-11ea-9e91-58defaeae8ae.png)

**Comment by neatek** [comment]
hello, i already got this issue from user in our discord server - https://discord.gg/J7eSXuU
i need time to check it. you can use old version - https://neatek.ru/en/plugins/neatek-gamevoting-old-plugin-versions-archived

**Comment by lucky84** [comment]
ok thank you

**Comment by neatek** [comment]
Can you check server command after ban? Is it correct?
ServerCommand (sm_ban) logging added to gv logs.
This row with command will be after `[gv.smx] Player RONALDO([U:1:848312288]) was banned by voting`
Download smx - https://github.com/neatek/GameVoting/raw/master/addons/sourcemod/plugins/gv.smx

**Comment by neatek** [comment]
Detected that this issue only with sourcebans. **Without sourcebans all fine.**
Check if working this command or not:
`sm_ban #USER_ID 1 "Gamevoting (neatek)(Toxic Player)"`
for test. where #USER_ID you can take from `status` 
#143 "Quade"             BOT                                     active
143 - it is #USER_ID

Also,
type `sm_ban` on server console. and write here answer.
Ex:
```
] sm_ban
[SM] Usage: sm_ban <#userid|name> <minutes|0> [reason]
```

**Comment by lucky84** [comment]
no command found like sm_ban, i found only this:

L 02/12/2020 - 16:13:22: "RONALDO<34><[U:1:848312288]><CT>" disconnected (reason "Banned by GameVoting (Empty reason)")

**Comment by neatek** [comment]
> no command found like sm_ban, i found only this:
> 
> L 02/12/2020 - 16:13:22: "RONALDO<34><[U:1:848312288]>" disconnected (reason "Banned by GameVoting (Empty reason)")

Update for latest version of _GameVoting_, it is now **1.9.1**

Also for testing you can use:
`sm_rcon bot_quota 20;sm_cvar gamevoting_bots_enabled 1;sm_cvar gamevoting_voteban_percent 0.1`

It will enable instantaneous voting for ban someone, for bot maybe if you choose it

Also,
type `sm_ban` on server console. and write here answer.
Ex:
```
] sm_ban
[SM] Usage: sm_ban <#userid|name> <minutes|0> [reason]
```

our discord server - https://discord.gg/J7eSXuU
You can type in `gamevoting` channel

**Comment by lucky84** [comment]
ok, I'll test it and let you know, thanks

**Comment by lucky84** [comment]
] sm_ban
[SourceBans] Usage: sm_ban <#userid|name> <time|0> [reason]

**Comment by neatek** [comment]
> ] sm_ban
> [SourceBans] Usage: sm_ban <#userid|name> <time|0> [reason]

Try to ban youself by `voteban`, see in gv logs something like this **but only for you situation**
`Server command: sm_ban #116 20 "Gamevoting (neatek)(Toxic Player)"`

And try to send (`sm_ban #116 20 "Gamevoting (neatek)(Toxic Player)`) manually this command to console what will you see?

Compare your #user_id from this command and from `status` command, its different?

**Comment by lucky84** [comment]
I can't let you know tomorrow. Must go to work now, sry

**Comment by neatek** [comment]
> I can't let you know tomorrow. Must go to work now, sry

What with bans? Are they working? It is problem with SourceBans anyway

**Comment by lucky84** [comment]
currently I can not test it, there are always players on the server -.-

**Comment by lucky84** [comment]
Votekick it works. From gv02-14.txt Log:
L 02/14/2020 - 16:05:52: [gv.smx] Player G.......(STEAM_0:0:xxxxxx) voted for kick Paul(BOT). (1/0)
L 02/14/2020 - 16:05:52: [gv.smx] Player Paul(BOT) was kicked by voting. (Last voted player: G.......)

and from server log:

L 02/14/2020 - 16:05:46: "G.........<8><[U:1:xxxxxx]><TERRORIST>" say "votekick"
L 02/14/2020 - 16:05:52: "Paul<9><BOT><CT>" disconnected (reason "Kicked by GameVoting (wait: 60sec)")


voteban.
From gv02-14.txt Log:

L 02/14/2020 - 16:06:10: [gv.smx] Player G.........(STEAM_0:0:1xxxxxxx) started public vote for ban Ron(BOT). Reason = Team Killing/Attacking
L 02/14/2020 - 16:06:17: [gv.smx] Player G...........(STEAM_0:0:1xxxxxx) voted for ban Connor(BOT). (1/0) (Reason: Team Killing/Attacking - #0)
L 02/14/2020 - 16:06:17: [gv.smx] Player Connor(BOT) was banned by voting. (Last voted player: G...........)
L 02/14/2020 - 16:06:17: [gv.smx] Server command: sm_ban #1692 1 "Gamevoting (G........)(Team Killing/Attacking)"

and from server log:

L 02/14/2020 - 16:19:22: "G........<8><[U:1:xxxxxxx]><CT>" say "voteban"
L 02/14/2020 - 16:19:27: "Rick<4001><BOT><TERRORIST>" disconnected (reason "Banned by GameVoting (Team Killing/Attacking)")

**Comment by lucky84** [comment]
voteban.

L 02/14/2020 - 16:06:10: [gv.smx] Player G.........(STEAM_0:0:1xxxxxxx) started public vote for ban Ron(BOT). Reason = Team Killing/Attacking
L 02/14/2020 - 16:06:17: [gv.smx] Player G...........(STEAM_0:0:1xxxxxx) voted for ban Connor(BOT). (1/0) (Reason: Team Killing/Attacking - #0)
L 02/14/2020 - 16:06:17: [gv.smx] Player Connor(BOT) was banned by voting. (Last voted player: G...........)
L 02/14/2020 - 16:06:17: [gv.smx] Server command: sm_ban #1692 1 "Gamevoting (G........)(Team Killing/Attacking)"

**Comment by lucky84** [comment]
> > ] sm_ban
> > [SourceBans] Usage: sm_ban <#userid|name> <time|0> [reason]
> 
> Try to ban youself by `voteban`, see in gv logs something like this **but only for you situation**
> `Server command: sm_ban #116 20 "Gamevoting (neatek)(Toxic Player)"`
> 
> And try to send (`sm_ban #116 20 "Gamevoting (neatek)(Toxic Player)`) manually this command to console what will you see?
> 
> Compare your #user_id from this command and from `status` command, its different?


L02/14/2020 - 16:40:07: rcon from "109.xx.xxx.xx:54xx4": command "sm_ban #4017 20 "Gamevoting (asdasd)(Toxic Player)""
L02/14/2020 - 16:40:07: rcon from "88.198.27.9:40730": command "status"
L02/14/2020 - 16:40:07: rcon from "88.198.27.9:40730": command ""
L02/14/2020 - 16:40:07: "G.......<4017><[U:1:xxxxxx]><Spectator>" disconnected (reason "Sie wurden von diesem Server gebannt, weitere Informationen auf https://www.xxxxxxxxx.de")
L02/14/2020 - 16:40:07: World triggered "Round_Draw" (CT "4") (T "1")
L02/14/2020 - 16:40:07: Team "CT" scored "4" with "0" players
L02/14/2020 - 16:40:07: Team "TERRORIST" scored "1" with "0" players
L02/14/2020 - 16:40:07: World triggered "Round_End"
L02/14/2020 - 16:40:16: World triggered "Round_Start"

![Anmerkung 2020-02-14 164503](https://user-images.githubusercontent.com/4884795/74545607-6e4d7b80-4f49-11ea-859e-e70fc7f481bb.png)

**Comment by crashzk** [comment]
@lucky84 I don't know if it helps, or if the problem would be that, but the SourceBans++ in the new versions changed its natives:
```
SBBanPlayer
SBPP_BanPlayer
SBPP_ReportPlayer
```
https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/include/sourcebanspp.inc

Could it be that? GameVoting may only support a new version of SB.

From what I could see you use a very old version of SourceBans `1.4.11` you can try to update it and check if the problem occurs in the current version of [SourceBans++](https://github.com/sbpp/sourcebans-pp/releases).

**Comment by neatek** [comment]
v1.9.2
- Supports: Sourcebans++, MaterialAdmin
- Cvar `gamevoting_startvote_enable` fixed.
