### ISSUE TITLE
Disable public votes

### ISSUE THREAD

**Issue by lucky84** [neatek/GameVoting#40]
I turned it off but it doesn't work.

> // Disable of enable public votes (def:1)
> // -
> // Default: "1"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> gamevoting_startvote_enable "0"

Players can still be a Public vote

**Comment by neatek** [comment]
Please check if voteban is working properly, then we will fix this issue.

**Comment by Noveio** [comment]
Та же проблема.
Ставлю gamevoting_startvote_enable "0".
Но запускает паблик голосование.

**Comment by neatek** [comment]
v1.9.2
Fixed
