### ISSUE TITLE
Implement voting system by menu

### ISSUE THREAD

**Issue by crashzk** [neatek/GameVoting#44]
Implement menu voting system

### HOW IT WORKS
Currently when players want to make a vote they do it by chat, example:
- `votekick` ai chooses the player to kick and the other players have to do the same thing.

The new version would be, a player starts a vote, no matter what, instead of all players having to write in the chat to vote too, it would automatically open a menu, something like that CSGO already has to vote to expel, change the map , as the name of the player who started the vote and its target, then everyone would vote for this menu.

It would be interesting to create a CVAR to control this voting mode, if the player wants the current one he leaves `1` if he wanted the new voting system to change to`0`.

**Comment by neatek** [comment]
You can check it

`gamevoting_startvote_enable 1`
