### ISSUE TITLE
Ban Reason

### ISSUE THREAD

**Issue by lucky84** [neatek/GameVoting#5]
Hi,

New Version Work Good, but the Ban Reason is really crap, see

"Gamevoting (Reason: Team Killing, votecaller: ¤R3D¤-¤F0X¤.tm)"

can you make this so

"_Player name_ has been banned by Gamevoting. Reason: Team Killing" for other votes too pls Thx :)

**Comment by neatek** [comment]
Please, open a new issue for gv1.8.3, thanks!
