### ISSUE TITLE
Votemutes are not displayed in sourcebans

### ISSUE THREAD

**Issue by phaiz** [neatek/GameVoting#6]
Votebans are entered into the Sourcebans database thus showing it on the bans page. Votemutes however are not entered into the Sourcebans database and are not shown on the comms page of a Sourcebans install. 

If possible, mutes/gags/whatever should also be displayed with all relevant information just as bans are. Perhaps it needs to use the Sourcebans database?

**Comment by Toakan** [comment]
This seems to be a straight SQL change to insert the mute into SourceBans.

**Comment by neatek** [comment]
comms page is in a extended version of source band which is not supported

**Comment by phaiz** [comment]
Other vote plugins use sourcebans. This one would see more users, maybe even myself, if it did as well.

**Comment by neatek** [comment]
Sourcebans supported. But not BaseComms.

**Comment by neatek** [comment]
Fixed. GV1.8.3Dev
+basecomm support.
